language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
install:
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - npm install npm
  - npm install polyclay
  - "./node_modules/.bin/npm install"
